{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "d7c7bec5-6e5f-46c7-8edc-d71a3ee53d93",
   "metadata": {},
   "outputs": [
    {
     "ename": "ZeroDivisionError",
     "evalue": "division by zero",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mZeroDivisionError\u001b[0m                         Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[1], line 8\u001b[0m\n\u001b[1;32m      5\u001b[0m \u001b[38;5;124;03m''' The program terminates abruptly when exception is not handled '''\u001b[39;00m\n\u001b[1;32m      7\u001b[0m a\u001b[38;5;241m=\u001b[39m\u001b[38;5;241m5\u001b[39m\n\u001b[0;32m----> 8\u001b[0m \u001b[43ma\u001b[49m\u001b[38;5;241;43m/\u001b[39;49m\u001b[38;5;241;43m0\u001b[39;49m\n\u001b[1;32m     10\u001b[0m \u001b[38;5;124;03m''' Q3 '''\u001b[39;00m\n\u001b[1;32m     12\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n",
      "\u001b[0;31mZeroDivisionError\u001b[0m: division by zero"
     ]
    }
   ],
   "source": [
    "''' Q1 '''\n",
    "''' The error implies a problem that mostly arises due to the shortage of system resources. On the other hand, the exceptions occur during runtime and compile time. '''\n",
    "\n",
    "''' Q2 '''\n",
    "''' The program terminates abruptly when exception is not handled '''\n",
    "\n",
    "a=5\n",
    "a/0\n",
    "\n",
    "''' Q3 '''\n",
    "\n",
    "try:\n",
    "    f = open(\"test5\",\"r\")\n",
    "    f.read()\n",
    "except Exception as e:\n",
    "    print(\"The exception has occurred \",e)\n",
    "else:\n",
    "    f.close()\n",
    "    print(\"Indise else block\")\n",
    "finally:\n",
    "    print(\"Finally is is executed\")\n",
    "\n",
    "''' Q4 '''\n",
    "\n",
    "''' a '''\n",
    "try:\n",
    "    f = open(\"test5\",\"r\")\n",
    "    f.read()\n",
    "except Exception as e:\n",
    "    print(\"The exception has occurred \",e)\n",
    "else:\n",
    "    f.close()\n",
    "    print(\"Indise else block\")\n",
    "finally:\n",
    "    print(\"Finally is is executed\")\n",
    "\n",
    "''' b '''\n",
    "try:\n",
    "    f = open(\"test5\",\"r\")\n",
    "    f.read()\n",
    "except Exception as e:\n",
    "    print(\"The exception has occurred \",e)\n",
    "else:\n",
    "    f.close()\n",
    "    print(\"Indise else block\")\n",
    "finally:\n",
    "    print(\"Finally is is executed\")\n",
    "\n",
    "''' c '''\n",
    "class validateAge(Exception):\n",
    "    def __init__(self,msg):\n",
    "        self.msg = msg\n",
    "\n",
    "def checkAge(age):\n",
    "    if age < 0 :\n",
    "        raise validateAge(\"Age entered is negeative\")\n",
    "    if age > 200:\n",
    "        raise validateAge(\"Age enetred is more than 200\")\n",
    "    else:\n",
    "        print(\"Age is valid\")\n",
    "\n",
    "try:\n",
    "    age = int(input(\"Enter the age\"))\n",
    "    checkAge(2000)\n",
    "except validateAge as e:\n",
    "    print(e)\n",
    "\n",
    "''' Q5 '''\n",
    "''' Built-in exceptions offer information about Python-related problems, and custom exceptions will add information about project-related problems '''\n",
    "\n",
    "class validateAge(Exception):\n",
    "    def __init__(self,msg):\n",
    "        self.msg = msg\n",
    "\n",
    "def checkAge(age):\n",
    "    if age < 0 :\n",
    "        raise validateAge(\"Age entered is negeative\")\n",
    "    if age > 200:\n",
    "        raise validateAge(\"Age enetred is more than 200\")\n",
    "    else:\n",
    "        print(\"Age is valid\")\n",
    "\n",
    "try:\n",
    "    age = int(input(\"Enter the age\"))\n",
    "    checkAge(2000)\n",
    "except validateAge as e:\n",
    "    print(e)\n",
    "\n",
    "''' Q6 '''\n",
    "class validateAge(Exception):\n",
    "    def __init__(self,msg):\n",
    "        self.msg = msg\n",
    "\n",
    "def checkAge(age):\n",
    "    if age < 0 :\n",
    "        raise validateAge(\"Age entered is negeative\")\n",
    "    if age > 200:\n",
    "        raise validateAge(\"Age enetred is more than 200\")\n",
    "    else:\n",
    "        print(\"Age is valid\")\n",
    "\n",
    "try:\n",
    "    age = int(input(\"Enter the age\"))\n",
    "    checkAge(2000)\n",
    "except validateAge as e:\n",
    "    print(e)\n",
    " "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "bed65a37-300e-41c1-8eea-73fea7e0fc39",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.8"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
